from app.models.user import User
from app.models.role import Role
from app.models.user_role import UserRole
from app.models.coordinator_user import CoordinatorUser
from app.models.audit_log import AuditLog
from app.models.training import Training
from app.models.training_participant import TrainingParticipant
from app.models.email_template import EmailTemplate
from app.models.email_log import EmailLog
from app.models.email_log_training import EmailLogTraining
from app.models.attendance import Attendance
from app.models.attendance_session import AttendanceSession
from app.models.assessment import Assessment
from app.models.assessment_question import AssessmentQuestion
from app.models.assessment_option import AssessmentOption
from app.models.assessment_attempt import AssessmentAttempt
from app.models.assessment_answer import AssessmentAnswer